### ISSUE TITLE
Which SDmodel do you use?

### ISSUE THREAD

**Issue by zackhxn** [VinAIResearch/Dataset-Diffusion#2]
Hello!May I ask which sdmodel on huggingface you are using in this project?

**Comment by saksornr** [comment]
Hello, @zackhxn. I found out they mention vanila SD v2.1 by stability AI in the paper. 
[`stabilityai/stable-diffusion-2-1`](https://huggingface.co/stabilityai/stable-diffusion-2-1)

**Comment by quang-ngh** [comment]
We use the SDv2.1. However, you can use the SDv1.5 or SDv1.4, it also works!
