### ISSUE TITLE
`aggregate_attention` default parameter are wrong?

### ISSUE THREAD

**Issue by saksornr** [VinAIResearch/Dataset-Diffusion#3]
I encountered a bug while running Stable Diffusion 2.0 on my local machine (RTX 3090). Here are the details:

```
CUDA Version: 12.3
Driver Version: 545.23.06
pytorch: 1.12.1
```
The bug was identified in the function `aggregate_attention` within the codebase. Here's the snippet of the function:
```python
def aggregate_attention(
    attention_store: AttentionStoreClassPrompts,
    res: int,
    is_cross: bool,
    from_where: List[str] = ["up", "down", "mid"],
    **kwargs,
):
    out = []
    attention_maps = attention_store.get_average_attention(**kwargs)
    for location in from_where:
        for item in attention_maps[f"{location}_{'cross' if is_cross else 'self'}"]:
            if item.shape[2] == res:
                out.append(item)

            print("item.shape[2]:", item.shape[2])
    out = torch.cat(out, dim=1).mean(dim=1)
    return out.cpu()
```

The issue arose from filtering items based on their shape's third dimension (item.shape[2] == res). After debugging, I discovered that the default values for self_res and cross_res parameters should be 12, 24, and 48, instead of 32 and 16, as previously set.

To address this, I made the necessary adjustments in the gen_data_voc.sh script as follows:
```bash
CUDA_VISIBLE_DEVICES=0 python -m gen_data \
    --work-dir data/gen_voc \
    --json-path data/prompts/voc_prompts.json \
    --data-type voc \
    --sd-path $sd_path \
    --batch-size $batch_size \
    --self-res 24 \
    --cross-res 12 
```

This change successfully resolved the issue, but I want to confirm if it might impact the generation procedure or produce incorrect results.

Looking forward to your insights.

**Comment by quang-ngh** [comment]
Hello huak95, 
The resolution of self/cross attention should be 64-32-16-8 when the shape of original latent (sampled from vae) is (64,64). Can you double check the shape of the original latent?

**Comment by saksornr** [comment]
When i print out the last item shape dimension, I got this. Maybe this is not the shape of the original latent. 
But if i set the self-res, cross-res to 64-32-16-8 it won't get any item.

```
item.shape[2]: 24
item.shape[2]: 24
item.shape[2]: 24
item.shape[2]: 48
item.shape[2]: 48
item.shape[2]: 48
item.shape[2]: 48
item.shape[2]: 48
item.shape[2]: 24
item.shape[2]: 24
item.shape[2]: 12
```

**Comment by quang-ngh** [comment]
Can you double check the `height` and `width` of the config of the Unet that you use? It should be (64,64).

**Comment by pluinyiasnhg** [comment]
I faced the same problem when I used the sd2.1 model to generate images, because the sd2.1 synthesized image size is 768x768. It is recommended to change to sd1.5 or scale the image size to 512x512.

**Comment by quang-ngh** [comment]
Yes, the image's need to be 512x512. Or you can use SD2.1-base that set the default image size to be 512.
